### ISSUE TITLE
Investigate the information we can get from an async method due to compiler optimizations

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet-debugger#266]
cc: @jskeet

**Comment by iantalarico** [comment]
I'm also seeing a big gap between debug and release.  Shouldn't we still be able to get the same info in release builds with PDBs?

**Comment by iantalarico** [comment]
Is this fixed now?  Quoc can you close this and point to the PR that fixed this?

**Comment by quoctruong** [comment]
This is now fixed with https://github.com/GoogleCloudPlatform/google-cloud-dotnet-debugger/pull/338.
