### ISSUE TITLE
Const variables are not displayed by the debugger.

### ISSUE THREAD

**Issue by quoctruong** [GoogleCloudPlatform/google-cloud-dotnet-debugger#320]
Constant variables such as `const string constString = "blah"` are stored in the metadata so we need to parse the metadata to get their information.

**Comment by iantalarico** [comment]
Is this fixed now?  Quoc can you close this and point to the PR that fixed this?

**Comment by quoctruong** [comment]
This will be fixed with https://github.com/GoogleCloudPlatform/google-cloud-dotnet-debugger/pull/344
