### ISSUE TITLE
Provide downloadable version (not in docker)

### ISSUE THREAD

**Issue by sandcastle** [GoogleCloudPlatform/google-cloud-dotnet-debugger#365]
We have base docker images we use for our applications which are not easy to configure. It would be good if we could just download a compiled version of the application in as a zip/gzip from the Releases tab in GitHub, so we can manually add to our containers. This will save us time having to manually compile when we want to use a new version of the debugger.

**Comment by iantalarico** [comment]
We plan to have support for this in the next quarter or so.  What is the base of your current container?

**Comment by sandcastle** [comment]
@iantalarico - Debian x64 - We use the base .Net Core 2.1.x base containers (runtime and asp.net) and then add our customisations and configurations on top

**Comment by iantalarico** [comment]
@sandcastle Sorry for the lack of status here.  We are still planning to get working on this soon and will update when we have a more concrete date.
