### ISSUE TITLE
Debugger fails to recognize breakpoints of file paths with additional directories

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet-debugger#371]
When setting breakpoints in a UI if the breakpoint contains additional directories the breakpoint will not be hit.  For example if the breakpoint location is`src/cartservice/CartServiceImpl.cs:45` the breakpoint will not be hit but the breakpoint `CartServiceImpl.cs:45` will.

Repo steps:
1. Set up and deploy to GKE the [hipster shop app ](https://github.com/hrasadi/microservices-demo)by @hrasadi
1.  Set a breakpoint on CartServiceImpl.cs line 45 (by clicking with the UI) via the Stackdriver Debugger UI.
1.  Set a breakpoint on CartServiceImpl.cs line 45 (manually) via the Stackdriver Debugger UI.
1. Access the service. Only the second breakpoint will hit.

cc: @hrasadi

**Comment by iantalarico** [comment]
@quoctruong If you have a chance in the next few weeks could you take a look at this?

**Comment by quoctruong** [comment]
@iantalarico Sure, I'll TAL.

**Comment by quoctruong** [comment]
@iantalarico Do you mean 2 files `CartServiceImpl.cs` exists and we set breakpoint on both of them and only 1 of the breakpoint got hit?

**Comment by iantalarico** [comment]
There is only one `CartServiceImpl.cs` file.  When we set the path as `CartServiceImpl.cs` we hit the breakpoint.  When the path is `src/cartservice/CartServiceImpl.cs` the breakpoint never hits.   I think we need to do a best effort and search for the proper files.  For instance `src/cartservice/CartServiceImpl.cs`  doesn't exists we should look for `cartservice/CartServiceImpl.cs` if that doesn't exist look for `CartServiceImpl.cs`

Thoughts?

**Comment by quoctruong** [comment]
I think we have best logic matching in the debugger. There is probably a bug in that logic.

**Comment by iantalarico** [comment]
Ah okay I had thought we did too.  Is it possible its related to path separators?

**Comment by quoctruong** [comment]
This is fixed with https://github.com/GoogleCloudPlatform/google-cloud-dotnet-debugger/pull/373
